/**
 * @license
 * Copyright 2025 Qwen Code
 * SPDX-License-Identifier: Apache-2.0
 */

import { Storage } from '../config/storage.js';
import { persistUsageBeforeTranscriptDeletion } from './usageHistoryService.js';
import { getProjectHash } from '../utils/paths.js';
import path from 'node:path';
import fs from 'node:fs';
import { randomUUID } from 'node:crypto';
import readline from 'node:readline';
import type { Content, Part } from '@google/genai';
import * as jsonl from '../utils/jsonl-utils.js';
import type { HistoryGap } from '../utils/conversation-chain.js';
import { prepareTranscriptRecords } from '../utils/transcript-records.js';
import type {
  ChatCompressionRecordPayload,
  ChatRecord,
  FileHistorySnapshotRecordPayload,
  TitleSource,
  UiTelemetryRecordPayload,
} from './chatRecordingService.js';
import type { FileHistorySnapshot } from './fileHistoryService.js';
import {
  deserializeSnapshots,
  FILE_HISTORY_DIR,
  MAX_SNAPSHOTS,
  serializeSnapshot,
} from './fileHistoryService.js';
import { uiTelemetryService } from '../telemetry/uiTelemetry.js';
import { createDebugLogger } from '../utils/debugLogger.js';
import { readRuntimeStatus } from '../utils/runtimeStatus.js';
import {
  LITE_READ_BUF_SIZE,
  readLastJsonStringFieldSync,
  readLastJsonStringFieldsSync,
} from '../utils/sessionStorageUtils.js';
import { getUsageOutputTokenCountForPromptEstimate } from './tokenEstimation.js';
import {
  isSessionArtifactRecord,
  rebuildSessionArtifactSnapshot,
  remapSessionArtifactPayloadForFork,
  type RebuiltSessionArtifactSnapshot,
} from './session-artifact-persistence.js';
import { SessionOrganizationService } from './session-organization-service.js';
import { SessionTranscriptTooLargeError } from './session-transcript-reader.js';
import { isValidSessionFileName } from '../utils/session-id.js';

const debugLogger = createDebugLogger('SESSION');

/**
 * Session item for list display.
 * Contains essential info extracted from the first record of a session file.
 */
export interface SessionListItem {
  /** Unique session identifier */
  sessionId: string;
  /** Working directory at session start */
  cwd: string;
  /** ISO 8601 timestamp when session started */
  startTime: string;
  /** File modification time (used for ordering and pagination) */
  mtime: number;
  /** First user prompt text (truncated for display) */
  prompt: string;
  /** Git branch at session start, if available */
  gitBranch?: string;
  /** Full path to the session file */
  filePath: string;
  /**
   * Number of unique-UUID user/assistant messages, when known. Listing
   * does NOT compute this — counting requires a full readline pass over
   * the JSONL and was the dominant cost of `listSessions` once a project
   * accumulated many sessions. Use {@link SessionService.countSessionMessages}
   * (or compute from the resumed conversation) when the count is needed.
   */
  messageCount?: number;
  /** Custom title set via /rename or auto-generated by the title service, if any */
  customTitle?: string;
  /**
   * Source of {@link customTitle}. `undefined` on legacy records without a
   * source field — consumers should treat `undefined` and `'manual'` the
   * same way for display (full-contrast). UI affordances like dimming are
   * reserved for `'auto'` so users can tell a model guess from a name they
   * chose.
   */
  titleSource?: TitleSource;
  /** Id of the session that spawned this one (via `create_sub_session`), if
   * any. Read from the transcript's `parent_session` record. Absent for a
   * top-level session. */
  parentSessionId?: string;
  /** Immutable creator attribution read from `session_source`. */
  sourceType?: string;
  /** Optional source-specific identifier paired with `sourceType`. */
  sourceId?: string;
  /** True when the item was read from the archive directory. */
  isArchived?: boolean;
}

export type SessionArchiveState = 'active' | 'archived';

export type SessionLocation = SessionArchiveState | 'conflict' | undefined;

/**
 * Pagination options for listing sessions.
 */
export interface ListSessionsOptions {
  /**
   * Cursor for pagination (mtime of the last item from previous page).
   * Items with mtime < cursor will be returned.
   * If undefined, starts from the most recent.
   */
  cursor?: number;
  /**
   * Maximum number of items to return.
   * @default 20
   */
  size?: number;
  /**
   * Which session directory to list.
   * @default 'active'
   */
  archiveState?: SessionArchiveState;
}

/**
 * Result of listing sessions with pagination info.
 */
export interface ListSessionsResult {
  /** Session items for this page */
  items: SessionListItem[];
  /**
   * Cursor for next page (mtime of last item).
   * Undefined if no more items.
   */
  nextCursor?: number;
  /** Whether there are more items after this page */
  hasMore: boolean;
}

/**
 * Aggregate persisted-session counts for a workspace.
 *
 * Built by scanning local JSONL files. This is intentionally separate from
 * {@link listSessions} so paginated list callers are not forced into a full
 * disk walk.
 */
export interface SessionInfoCounts {
  /** Persisted active (non-archived) sessions belonging to this project. */
  active: number;
  /** Persisted archived sessions belonging to this project. */
  archived: number;
  /** `active + archived`. */
  total: number;
  /**
   * True when the scan could not classify every candidate session file, so
   * counts may be lower than the true population.
   */
  truncated: boolean;
}

/**
 * Result of removing multiple sessions.
 */
export interface RemoveSessionsResult {
  removed: string[];
  notFound: string[];
  errors: Array<{ sessionId: string; error: Error }>;
}

export interface ArchiveSessionsResult {
  archived: string[];
  alreadyArchived: string[];
  notFound: string[];
  errors: Array<{ sessionId: string; error: Error }>;
}

export interface ArchiveSessionsOptions {
  knownLocation?: 'active';
}

export interface UnarchiveSessionsResult {
  unarchived: string[];
  alreadyActive: string[];
  notFound: string[];
  errors: Array<{ sessionId: string; error: Error }>;
}

export interface UnarchiveSessionsOptions {
  knownLocation?: 'archived';
}

export interface SessionServiceOptions {
  onWarning?: (message: string) => void;
  runtimeBaseDir?: string;
}

/**
 * Complete conversation reconstructed from ChatRecords.
 * Used for resuming sessions and API compatibility.
 */
export interface ConversationRecord {
  sessionId: string;
  projectHash: string;
  startTime: string;
  lastUpdated: string;
  /** Messages in chronological order (reconstructed from tree) */
  messages: ChatRecord[];
}

/**
 * Data structure for resuming an existing session.
 */
export interface ResumedSessionData {
  conversation: ConversationRecord;
  filePath: string;
  /** UUID of the last completed message - new messages should use this as parentUuid */
  lastCompletedUuid: string | null;
  /** Deserialized file history snapshots for resume (enables /rewind across sessions) */
  fileHistorySnapshots?: FileHistorySnapshot[];
  /** Persisted session artifact metadata reconstructed from JSONL records. */
  artifactSnapshot?: RebuiltSessionArtifactSnapshot;
  /**
   * Breaks in the persisted parentUuid chain that were detected during
   * reconstruction (an earlier segment of history was physically lost and could
   * not be recovered). Lets the surface render a visible gap divider. Undefined
   * when the chain was intact.
   */
  historyGaps?: HistoryGap[];
}

/**
 * Maximum number of files to process when listing sessions.
 * This is a safety limit to prevent performance issues with very large chat directories.
 */
const MAX_FILES_TO_PROCESS = 10000;

/**
 * Maximum character length for a session custom title.
 * Shared across CLI, WebUI, VSCode, and ACP.
 */
export const SESSION_TITLE_MAX_LENGTH = 200;

/**
 * Pattern for validating session file names.
 * Session files are named as `${sessionId}.jsonl`, using either the legacy
 * UUID-like identifier or the current UUID with an optional agent suffix.
 */
/** Maximum number of lines to scan when looking for the first prompt text. */
const MAX_PROMPT_SCAN_LINES = 10;
/**
 * Maximum bytes to read from head/tail of a session file.
 * Used by readLastRecordUuid which still does its own tail read.
 */
const TAIL_READ_SIZE = 64 * 1024;

async function copyFileHistoryBackups(
  sourceSessionId: string,
  targetSessionId: string,
): Promise<void> {
  const fsPromises = await import('node:fs/promises');
  const sourceDir = path.join(
    Storage.getGlobalQwenDir(),
    FILE_HISTORY_DIR,
    sourceSessionId,
  );
  const targetDir = path.join(
    Storage.getGlobalQwenDir(),
    FILE_HISTORY_DIR,
    targetSessionId,
  );

  let entries: string[];
  try {
    entries = await fsPromises.readdir(sourceDir);
  } catch (e: unknown) {
    if ((e as NodeJS.ErrnoException).code === 'ENOENT') return;
    debugLogger.warn(`copyFileHistoryBackups: readdir failed: ${e}`);
    return;
  }
  if (entries.length === 0) return;

  try {
    await fsPromises.mkdir(targetDir, { recursive: true });
  } catch (e) {
    debugLogger.warn(`copyFileHistoryBackups: mkdir failed: ${e}`);
    return;
  }
  await Promise.all(
    entries.map(async (name) => {
      const src = path.join(sourceDir, name);
      const dst = path.join(targetDir, name);
      try {
        await fsPromises.link(src, dst);
      } catch {
        try {
          await fsPromises.copyFile(src, dst);
        } catch (copyErr) {
          debugLogger.warn(
            `copyFileHistoryBackups: failed to copy ${name}: ${copyErr}`,
          );
        }
      }
    }),
  );
}

/**
 * Service for managing chat sessions.
 *
 * This service handles:
 * - Listing sessions with pagination (ordered by mtime)
 * - Loading full session data for resumption
 * - Removing sessions
 *
 * Sessions are stored as JSONL files, one per session.
 * File location: ~/.qwen/tmp/<project_id>/chats/
 */
export class SessionService {
  private readonly storage: Storage;
  private readonly projectHash: string;
  private readonly projectRoot: string;
  private readonly onWarning: ((message: string) => void) | undefined;

  constructor(cwd: string, options: SessionServiceOptions = {}) {
    this.storage = new Storage(cwd, options.runtimeBaseDir);
    this.projectRoot = cwd;
    this.projectHash = getProjectHash(cwd);
    this.onWarning = options.onWarning;
  }

  /** The workspace root this service is bound to (the cwd it was constructed
   * with). Lets callers that already hold a service — e.g. the session
   * archive/delete choke points — reach per-project state such as the durable
   * scheduled-tasks file without re-plumbing the workspace path. */
  getProjectRoot(): string {
    return this.projectRoot;
  }

  private warn(message: string): void {
    debugLogger.warn(message);
    this.onWarning?.(message);
  }

  private getChatsDir(): string {
    return path.join(this.storage.getProjectDir(), 'chats');
  }

  private getArchiveChatsDir(): string {
    return path.join(this.getChatsDir(), 'archive');
  }

  private getChatsDirForState(state: SessionArchiveState): string {
    return state === 'archived'
      ? this.getArchiveChatsDir()
      : this.getChatsDir();
  }

  private getSessionFilePath(
    sessionId: string,
    state: SessionArchiveState,
  ): string {
    return path.join(this.getChatsDirForState(state), `${sessionId}.jsonl`);
  }

  private getWorktreeSessionPathForState(
    sessionId: string,
    state: SessionArchiveState,
  ): string {
    return path.join(
      this.getChatsDirForState(state),
      `${sessionId}.worktree.json`,
    );
  }

  private async sessionBelongsToCurrentProject(
    sessionId: string,
    recordCwd: string,
  ): Promise<boolean> {
    if (getProjectHash(recordCwd) === this.projectHash) {
      return true;
    }

    // Worktree sessions record cwd as the worktree path
    // (<repoRoot>/.qwen/worktrees/<slug>), which has a different project
    // hash. Infer the repo root from the path and check its hash. This
    // is durable — it doesn't depend on the sidecar file, which is
    // transient and cleared when the worktree is removed. Pure string
    // ops, so check before the file-read runtime status below.
    // Use lastIndexOf to handle nested worktrees: for
    // /repo/.qwen/worktrees/parent/.qwen/worktrees/child, the innermost
    // marker gives repoRoot = /repo/.qwen/worktrees/parent (the workspace).
    const worktreesMarker = `${path.sep}.qwen${path.sep}worktrees${path.sep}`;
    const markerIdx = recordCwd.lastIndexOf(worktreesMarker);
    if (markerIdx > 0) {
      const repoRoot = recordCwd.substring(0, markerIdx);
      if (getProjectHash(repoRoot) === this.projectHash) {
        return true;
      }
    }

    const status = await readRuntimeStatus(
      this.storage.getRuntimeStatusPath(sessionId),
    );
    return (
      status?.sessionId === sessionId &&
      getProjectHash(status.workDir) === this.projectHash
    );
  }

  /**
   * Returns the absolute path to the sidecar JSON file that stores
   * worktree session state for the given session id. The file may not
   * exist yet — consumers must handle ENOENT as "no active worktree".
   */
  getWorktreeSessionPath(sessionId: string): string {
    return this.getWorktreeSessionPathForState(sessionId, 'active');
  }

  getWorktreeSessionPathForArchiveState(
    sessionId: string,
    state: SessionArchiveState,
  ): string {
    return this.getWorktreeSessionPathForState(sessionId, state);
  }

  private async readProjectSessionHead(
    sessionId: string,
    filePath: string,
  ): Promise<ChatRecord | undefined> {
    try {
      const records = await jsonl.readLines<ChatRecord>(filePath, 1);
      if (records.length === 0) {
        return undefined;
      }
      const firstRecord = records[0];
      if (
        !(await this.sessionBelongsToCurrentProject(sessionId, firstRecord.cwd))
      ) {
        return undefined;
      }
      return firstRecord;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return undefined;
      }
      this.warn(`readProjectSessionHead: failed to read ${filePath}: ${error}`);
      throw error;
    }
  }

  /**
   * Reads the persisted `parentSessionId` for a single session (active or
   * archived), or undefined when it has no parent. Used to re-seed a live entry
   * on restore/resume so a restored sub-session's status still reports its
   * lineage after a daemon restart. Best-effort: a read failure returns
   * undefined rather than throwing — a missing link must never fail a restore.
   */
  async readParentSessionId(sessionId: string): Promise<string | undefined> {
    return (await this.readCreationMetadata(sessionId)).parentSessionId;
  }

  /** Reads immutable creation metadata for an active or archived session. */
  async readCreationMetadata(sessionId: string): Promise<{
    parentSessionId?: string;
    sourceType?: string;
    sourceId?: string;
  }> {
    for (const state of ['active', 'archived'] as const) {
      const filePath = this.getSessionFilePath(sessionId, state);
      try {
        const records = await jsonl.readLines<ChatRecord>(
          filePath,
          MAX_PROMPT_SCAN_LINES,
        );
        if (records.length === 0) continue;
        if (
          !(await this.sessionBelongsToCurrentProject(
            records[0].sessionId,
            records[0].cwd,
          ))
        ) {
          continue;
        }
        return this.extractCreationMetadataFromRecords(records);
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') continue;
        this.warn(
          `readCreationMetadata: failed to read ${sessionId}: ${error}`,
        );
      }
    }
    return {};
  }

  async getSessionLocation(sessionId: string): Promise<SessionLocation> {
    if (!isValidSessionFileName(`${sessionId}.jsonl`)) {
      return undefined;
    }

    const [active, archived] = await Promise.all([
      this.readProjectSessionHead(
        sessionId,
        this.getSessionFilePath(sessionId, 'active'),
      ),
      this.readProjectSessionHead(
        sessionId,
        this.getSessionFilePath(sessionId, 'archived'),
      ),
    ]);

    if (active && archived) return 'conflict';
    if (active) return 'active';
    if (archived) return 'archived';
    return undefined;
  }

  private removeFileIfExists(filePath: string): void {
    try {
      fs.unlinkSync(filePath);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        throw error;
      }
    }
  }

  private removeWorktreeSidecars(sessionId: string): void {
    for (const state of ['active', 'archived'] as const) {
      const sidecar = this.getWorktreeSessionPathForState(sessionId, state);
      if (fs.existsSync(sidecar)) {
        this.removeFileIfExists(sidecar);
      }
    }
  }

  private removeFileHistoryBackups(sessionId: string): void {
    fs.rmSync(
      path.join(Storage.getGlobalQwenDir(), FILE_HISTORY_DIR, sessionId),
      { recursive: true, force: true },
    );
  }

  private async removeSessionOrganization(sessionId: string): Promise<void> {
    try {
      await new SessionOrganizationService(this.projectRoot, (message) => {
        this.warn(message);
      }).removeSession(sessionId);
    } catch (error) {
      this.warn(
        `removeSession: failed to clear session organization for ${sessionId}: ${error}`,
      );
    }
  }

  private async removeSessionOrganizations(
    sessionIds: string[],
  ): Promise<void> {
    if (sessionIds.length === 0) return;
    try {
      await new SessionOrganizationService(this.projectRoot, (message) => {
        this.warn(message);
      }).removeSessions(sessionIds);
    } catch (error) {
      this.warn(
        `removeSessions: failed to clear session organization for ${sessionIds.join(
          ', ',
        )}: ${error}`,
      );
    }
  }

  private moveOptionalFile(sourcePath: string, targetPath: string): boolean {
    if (!fs.existsSync(sourcePath)) {
      return false;
    }
    if (fs.existsSync(targetPath)) {
      throw new Error('Archive sidecar conflict: destination already exists');
    }
    fs.mkdirSync(path.dirname(targetPath), { recursive: true });
    fs.renameSync(sourcePath, targetPath);
    return true;
  }

  private sessionFileMoveError(
    action: 'archive' | 'unarchive',
    error: unknown,
  ): Error {
    const code = (error as NodeJS.ErrnoException).code ?? 'unknown error';
    return new Error(`Failed to ${action} session file: ${code}`);
  }

  /**
   * Reads the session title from a JSONL file.
   *
   * Delegates to {@link readLastJsonStringFieldSync}, which scans the tail
   * window first (fast path; almost always hits because finalize() re-appends
   * the title on every lifecycle event) and falls back to a bounded head
   * window when the tail has no match. The `custom_title` line-marker guards
   * against false matches from user content that happens to include a
   * `customTitle` field.
   */
  private readSessionTitleFromFile(
    filePath: string,
    tailBuffer?: Buffer,
  ): string | undefined {
    // Match only on actual custom_title system records. `'custom_title'` as
    // a loose substring can land on a user message that happens to contain
    // the literal "custom_title" (code review of this very file, etc.);
    // requiring the full `"subtype":"custom_title"` pattern guarantees the
    // match is on a system record written by {@link writeLineSync}, which
    // JSON.stringifies records in a predictable compact form.
    return readLastJsonStringFieldSync(
      filePath,
      'customTitle',
      '"subtype":"custom_title"',
      tailBuffer,
    );
  }

  /**
   * Reads both the custom title and its source from a session file in a
   * single pass — the helper extracts both fields from the same matching
   * `custom_title` line, so the pair is always consistent (never one field
   * from an old record and another from a new one).
   *
   * `titleSource` is absent on legacy records written before the field was
   * introduced — callers treat `undefined` as equivalent to `'manual'` so a
   * user's pre-upgrade rename is never displayed as if it were auto-generated.
   */
  private readSessionTitleInfoFromFile(
    filePath: string,
    tailBuffer?: Buffer,
  ): {
    title?: string;
    source?: TitleSource;
  } {
    const hit = readLastJsonStringFieldsSync(
      filePath,
      'customTitle',
      ['titleSource'],
      '"subtype":"custom_title"',
      tailBuffer,
    );
    const title = hit['customTitle'];
    if (!title) return {};
    const rawSource = hit['titleSource'];
    const source =
      rawSource === 'auto' || rawSource === 'manual' ? rawSource : undefined;
    return { title, source };
  }

  /**
   * Extracts the `parent_session` record's `parentSessionId` from records
   * ALREADY read for the listing (the first {@link MAX_PROMPT_SCAN_LINES}), or
   * undefined when the session has no parent. The record is written once right
   * after the sub-session is created — before any prompt — so it is reliably
   * within that window. No extra file open, unlike the title (which re-anchors
   * at EOF and needs its own tail-then-head scan).
   */
  private extractCreationMetadataFromRecords(records: ChatRecord[]): {
    parentSessionId?: string;
    sourceType?: string;
    sourceId?: string;
  } {
    let parentSessionId: string | undefined;
    let sourceType: string | undefined;
    let sourceId: string | undefined;
    for (const record of records) {
      if (record.type === 'system' && record.subtype === 'parent_session') {
        const payload = record.systemPayload as
          | { parentSessionId?: unknown }
          | undefined;
        if (
          parentSessionId === undefined &&
          typeof payload?.parentSessionId === 'string'
        ) {
          parentSessionId = payload.parentSessionId;
        }
      }
      if (record.type === 'system' && record.subtype === 'session_source') {
        const payload = record.systemPayload as
          | { sourceType?: unknown; sourceId?: unknown }
          | undefined;
        if (
          sourceType === undefined &&
          typeof payload?.sourceType === 'string'
        ) {
          sourceType = payload.sourceType;
          sourceId =
            typeof payload.sourceId === 'string' ? payload.sourceId : undefined;
        }
      }
    }
    return {
      ...(parentSessionId ? { parentSessionId } : {}),
      ...(sourceType ? { sourceType } : {}),
      ...(sourceId !== undefined ? { sourceId } : {}),
    };
  }

  /**
   * Public accessor: returns both the current custom title and its source
   * for a given session. Used by `ChatRecordingService` on resume to
   * preserve the persisted `titleSource` rather than defaulting to manual.
   *
   * @remarks Only checks active sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  getSessionTitleInfo(sessionId: string): {
    title?: string;
    source?: TitleSource;
  } {
    if (!isValidSessionFileName(`${sessionId}.jsonl`)) {
      return {};
    }
    const chatsDir = this.getChatsDir();
    const filePath = path.join(chatsDir, `${sessionId}.jsonl`);
    return this.readSessionTitleInfoFromFile(filePath);
  }

  /**
   * Reads the UUID of the last record in a session JSONL file.
   * Uses a tail-read strategy for efficiency.
   *
   * Each physical line is routed through `jsonl.parseLineTolerant` so a
   * `}{`-glued tail line (#3606 corruption shape) still yields its records
   * instead of being silently skipped — otherwise `renameSession` would set
   * `custom_title.parentUuid` to a stale uuid and `reconstructHistory` would
   * truncate the chain on resume.
   */
  private readLastRecordUuid(filePath: string): string | null {
    try {
      const stats = fs.statSync(filePath);
      const fileSize = stats.size;
      const readStart = Math.max(0, fileSize - TAIL_READ_SIZE);
      const readLength = Math.min(fileSize, TAIL_READ_SIZE);

      const fd = fs.openSync(filePath, 'r');
      let buffer: Buffer;
      let firstSegmentIsPartial = false;
      try {
        buffer = Buffer.alloc(readLength);
        fs.readSync(fd, buffer, 0, readLength, readStart);

        // The first split segment is partial only when the tail window
        // truly starts in the middle of a JSONL record. If the byte right
        // before `readStart` is `\n`, the window started on a record
        // boundary and the first segment is a complete line — the
        // 64-KiB-aligned case where `prev\n<exactly-64KiB-record>\n`
        // would otherwise drop the only readable record. Peek that byte
        // before deciding to shift.
        if (readStart > 0) {
          const peek = Buffer.alloc(1);
          fs.readSync(fd, peek, 0, 1, readStart - 1);
          firstSegmentIsPartial = peek[0] !== 0x0a; // 0x0a = '\n'
        }
      } finally {
        fs.closeSync(fd);
      }

      const tail = buffer.toString('utf-8');
      const lines = tail.split('\n');

      // Discard the first segment ONLY when it's a true partial fragment.
      // Running tolerant recovery on a partial would surface a balanced
      // inner `{ "uuid": ... }` object from inside the record's payload as
      // if it were a top-level uuid — `renameSession` would then anchor
      // `custom_title.parentUuid` at payload data and break the parent
      // chain. Complete physical lines (including a boundary-aligned
      // first segment) are safe to recover.
      if (firstSegmentIsPartial) {
        lines.shift();
      }

      // Walk physical lines bottom-up; on each line walk recovered records
      // bottom-up too, so a `}{`-glued tail returns the *latest* record.
      for (let i = lines.length - 1; i >= 0; i--) {
        const trimmed = lines[i].trim();
        if (!trimmed) continue;
        const records = jsonl.parseLineTolerant<ChatRecord>(trimmed, filePath);
        for (let j = records.length - 1; j >= 0; j--) {
          const record = records[j];
          if (record.uuid) {
            return record.uuid;
          }
        }
      }

      return null;
    } catch {
      return null;
    }
  }

  /**
   * Extracts the first user prompt text from a Content object.
   */
  private extractPromptText(message: Content | undefined): string {
    if (!message?.parts) return '';

    for (const part of message.parts as Part[]) {
      if ('text' in part) {
        const textPart = part as { text: string };
        const text = textPart.text;
        // Truncate long prompts for display
        return text.length > 200 ? `${text.slice(0, 200)}...` : text;
      }
    }
    return '';
  }

  /**
   * Finds the first available prompt text by scanning the first N records,
   * preferring user messages. Returns an empty string if none found.
   */
  private extractFirstPromptFromRecords(records: ChatRecord[]): string {
    for (const record of records) {
      if (record.type !== 'user') continue;
      const prompt = this.extractPromptText(record.message);
      if (prompt) return prompt;
    }
    return '';
  }

  /**
   * Counts unique user/assistant message UUIDs in a session file by
   * streaming the JSONL line-by-line. Each physical line is routed
   * through `jsonl.parseLineTolerant` so a `}{`-glued line (#3606
   * corruption shape) still contributes both records, instead of being
   * silently dropped.
   *
   * Project-scoped: returns 0 if the file's first record belongs to a
   * different project. Sibling public methods (deleteSession,
   * renameSession, loadSession) apply the same first-record cwd check;
   * mirroring it here keeps lazy-count callers from accidentally
   * counting a session that lives in the shared chats directory but
   * belongs to another project.
   *
   * This is intentionally NOT called from {@link listSessions} or
   * {@link findSessionsByTitle} — it would be O(total bytes on disk) per
   * picker open, dominating wall time once a project accumulates dozens
   * of multi-MB sessions. Call this lazily, only when a specific
   * session's message count is about to be displayed (e.g., from a
   * preview panel) or computed from a resumed conversation.
   *
   * @remarks Only checks active sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  async countSessionMessages(sessionId: string): Promise<number> {
    if (!isValidSessionFileName(`${sessionId}.jsonl`)) {
      return 0;
    }
    const chatsDir = this.getChatsDir();
    const filePath = path.join(chatsDir, `${sessionId}.jsonl`);

    try {
      const firstRecords = await jsonl.readLines<ChatRecord>(filePath, 1);
      if (firstRecords.length === 0) return 0;
      if (
        !(await this.sessionBelongsToCurrentProject(
          sessionId,
          firstRecords[0].cwd,
        ))
      ) {
        return 0;
      }
    } catch {
      return 0;
    }

    return this.countSessionMessagesFromPath(filePath);
  }

  private async countSessionMessagesFromPath(
    filePath: string,
  ): Promise<number> {
    const uniqueUuids = new Set<string>();
    try {
      const fileStream = fs.createReadStream(filePath);
      const rl = readline.createInterface({
        input: fileStream,
        crlfDelay: Infinity,
      });

      for await (const line of rl) {
        const trimmed = line.trim();
        if (!trimmed) continue;
        for (const record of jsonl.parseLineTolerant<ChatRecord>(
          trimmed,
          filePath,
        )) {
          if (record.type === 'user' || record.type === 'assistant') {
            uniqueUuids.add(record.uuid);
          }
        }
      }

      return uniqueUuids.size;
    } catch {
      return 0;
    }
  }

  /**
   * Lists sessions for the current project with pagination.
   *
   * Sessions are ordered by file modification time (most recent first).
   * Uses cursor-based pagination with mtime as the cursor.
   *
   * Only reads the first line of each JSONL file for efficiency.
   * Files are filtered by UUID pattern first, then by project hash.
   *
   * @param options Pagination options
   * @returns Paginated list of sessions
   */
  async listSessions(
    options: ListSessionsOptions = {},
  ): Promise<ListSessionsResult> {
    const { cursor, size = 20, archiveState = 'active' } = options;
    const chatsDir = this.getChatsDirForState(archiveState);
    const isArchived = archiveState === 'archived';

    // Get all valid session files (matching UUID pattern) with their stats
    let files: Array<{ name: string; mtime: number }> = [];
    try {
      const fileNames = fs.readdirSync(chatsDir);
      for (const name of fileNames) {
        // Only process files matching session file pattern
        if (!isValidSessionFileName(name)) continue;
        const filePath = path.join(chatsDir, name);
        try {
          const stats = fs.statSync(filePath);
          files.push({ name, mtime: stats.mtimeMs });
        } catch {
          // Skip files we can't stat
          continue;
        }
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return { items: [], hasMore: false };
      }
      throw error;
    }

    // Sort by mtime descending (most recent first)
    files.sort((a, b) => b.mtime - a.mtime);

    // Apply cursor filter (items with mtime < cursor)
    if (cursor !== undefined) {
      files = files.filter((f) => f.mtime < cursor);
    }

    // Iterate through files until we have enough matching ones.
    // Different projects may share the same chats directory due to path sanitization,
    // so we need to filter by project hash and continue until we have enough items.
    const items: SessionListItem[] = [];
    let filesProcessed = 0;
    let lastProcessedMtime: number | undefined;
    let hasMoreFiles = false;

    // Pre-allocate the tail-read buffer once and pass it to every
    // per-file metadata read. Without pooling, each session in the
    // page allocs+GCs a fresh 64KB Buffer; for a typical page of 20
    // that's ~1.3MB churn per /resume open. The helper reuses this
    // same scratch buffer for its bounded tail and head-window reads.
    const tailBuffer = Buffer.alloc(LITE_READ_BUF_SIZE);

    for (const file of files) {
      // Safety limit to prevent performance issues
      if (filesProcessed >= MAX_FILES_TO_PROCESS) {
        hasMoreFiles = true;
        break;
      }

      // Stop if we have enough items
      if (items.length >= size) {
        hasMoreFiles = true;
        break;
      }

      filesProcessed++;
      lastProcessedMtime = file.mtime;

      const filePath = path.join(chatsDir, file.name);
      const records = await jsonl.readLines<ChatRecord>(
        filePath,
        MAX_PROMPT_SCAN_LINES,
      );

      if (records.length === 0) continue;
      const firstRecord = records[0];

      if (
        !(await this.sessionBelongsToCurrentProject(
          firstRecord.sessionId,
          firstRecord.cwd,
        ))
      ) {
        continue;
      }

      const prompt = this.extractFirstPromptFromRecords(records);

      const titleInfo = this.readSessionTitleInfoFromFile(filePath, tailBuffer);
      const source = this.extractCreationMetadataFromRecords(records);
      items.push({
        sessionId: firstRecord.sessionId,
        cwd: firstRecord.cwd,
        startTime: firstRecord.timestamp,
        mtime: file.mtime,
        prompt,
        gitBranch: firstRecord.gitBranch,
        filePath,
        // messageCount intentionally omitted — see SessionListItem
        // and `countSessionMessages` for the rationale.
        customTitle: titleInfo.title,
        titleSource: titleInfo.source,
        ...(source.parentSessionId
          ? { parentSessionId: source.parentSessionId }
          : {}),
        ...(source.sourceType ? { sourceType: source.sourceType } : {}),
        ...(source.sourceId !== undefined ? { sourceId: source.sourceId } : {}),
        isArchived,
      });
    }

    // Determine next cursor (mtime of last processed file)
    // Only set if there are more files to process
    const nextCursor =
      hasMoreFiles && lastProcessedMtime !== undefined
        ? lastProcessedMtime
        : undefined;

    return {
      items,
      nextCursor,
      hasMore: hasMoreFiles,
    };
  }

  /**
   * Counts persisted sessions for this project by scanning the active and
   * archived chats directories.
   *
   * Same disk-walk shape as {@link findSessionTitlesByPrefix} /
   * {@link findSessionsByTitle}: `readdir` the chats dir, cap at the
   * file-processing safety limit, then read only the first JSONL record for
   * project membership. Title/prompt/message hydration is skipped entirely.
   *
   * Still an O(n) disk walk — callers (and HTTP clients of
   * `GET .../session-info`) must not poll this in a tight loop.
   */
  async getSessionInfoCounts(): Promise<SessionInfoCounts> {
    const [active, archived] = await Promise.all([
      this.countSessionsInState('active'),
      this.countSessionsInState('archived'),
    ]);
    return {
      active: active.count,
      archived: archived.count,
      total: active.count + archived.count,
      truncated: active.truncated || archived.truncated,
    };
  }

  private async countSessionsInState(
    archiveState: SessionArchiveState,
  ): Promise<{ count: number; truncated: boolean }> {
    const chatsDir = this.getChatsDirForState(archiveState);
    let fileNames: string[];
    try {
      fileNames = fs.readdirSync(chatsDir);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return { count: 0, truncated: false };
      }
      throw error;
    }

    let count = 0;
    let filesProcessed = 0;
    let truncated = false;

    for (const name of fileNames) {
      if (!isValidSessionFileName(name)) continue;
      if (filesProcessed >= MAX_FILES_TO_PROCESS) {
        truncated = true;
        break;
      }
      filesProcessed++;

      const filePath = path.join(chatsDir, name);
      // Project filter only — same first-record membership check as
      // findSessionTitlesByPrefix, without the title tail-read (every file
      // is a candidate when counting).
      try {
        const records = await jsonl.readLines<ChatRecord>(filePath, 1);
        if (records.length === 0) {
          truncated = true;
          continue;
        }
        const firstRecord = records[0]!;
        if (
          !(await this.sessionBelongsToCurrentProject(
            firstRecord.sessionId,
            firstRecord.cwd,
          ))
        ) {
          continue;
        }
        count++;
      } catch {
        truncated = true;
        continue;
      }
    }

    return { count, truncated };
  }

  /**
   * Reads all records from a session file.
   */
  private async readAllRecords(filePath: string): Promise<ChatRecord[]> {
    try {
      return await jsonl.read<ChatRecord>(filePath);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        debugLogger.error('Error reading session file:', error);
      }
      return [];
    }
  }

  /**
   * Reconstructs a linear conversation from tree-structured records.
   *
   * Delegates validation, parentUuid walking, and fragment aggregation to the
   * shared transcript record preparation module. With
   * `detectGaps`, a walk that stops on a physically-missing parent records the
   * break in the returned `gaps` (see {@link HistoryGap}) so the surface can
   * mark it — the earlier records are NOT reconstructed (reconnecting them
   * could resurrect turns the user rewound away). Without `detectGaps` the
   * result is identical to the historical walk.
   */
  private reconstructHistory(
    records: ChatRecord[],
    opts?: { leafUuid?: string; detectGaps?: boolean },
  ): { messages: ChatRecord[]; gaps: HistoryGap[] } {
    if (records.length === 0) return { messages: [], gaps: [] };
    const prepared = prepareTranscriptRecords(records, {
      ...(opts?.leafUuid !== undefined ? { leafUuid: opts.leafUuid } : {}),
    });
    return {
      messages: prepared.records.map((record) => record as ChatRecord),
      gaps: opts?.detectGaps ? [...prepared.gaps] : [],
    };
  }

  /**
   * Loads a session by its session ID.
   * Reconstructs the full conversation from tree-structured records.
   *
   * @param sessionId The session ID to load
   * @returns Session data for resumption, or undefined if not found
   * @remarks Only checks active sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  async loadSession(
    sessionId: string,
  ): Promise<ResumedSessionData | undefined> {
    return this.loadSessionFromState(sessionId, 'active');
  }

  /**
   * Reads an archived session without changing its archive state.
   * Daemon load/resume paths must continue to use {@link loadSession}.
   */
  async loadArchivedSession(
    sessionId: string,
    options: { maxBytes: number },
  ): Promise<ResumedSessionData | undefined> {
    if (!isValidSessionFileName(`${sessionId}.jsonl`)) {
      return undefined;
    }
    const filePath = this.getSessionFilePath(sessionId, 'archived');
    let stats: fs.Stats;
    try {
      stats = fs.statSync(filePath);
      if (stats.size > options.maxBytes) {
        throw new SessionTranscriptTooLargeError(
          sessionId,
          stats.size,
          options.maxBytes,
        );
      }
    } catch (error) {
      if (error instanceof SessionTranscriptTooLargeError) {
        throw error;
      }
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        throw error;
      }
      return undefined;
    }
    return this.loadSessionFromState(sessionId, 'archived', stats);
  }

  private async loadSessionFromState(
    sessionId: string,
    state: SessionArchiveState,
    stats?: fs.Stats,
  ): Promise<ResumedSessionData | undefined> {
    const filePath = this.getSessionFilePath(sessionId, state);

    const records = await this.readAllRecords(filePath);
    if (records.length === 0) {
      return;
    }

    const firstRecord = records[0];
    if (
      !(await this.sessionBelongsToCurrentProject(
        firstRecord.sessionId,
        firstRecord.cwd,
      ))
    ) {
      return;
    }

    // Reconstruct linear history
    const { messages, gaps } = this.reconstructHistory(records, {
      detectGaps: true,
    });
    if (messages.length === 0) {
      return;
    }

    if (gaps.length > 0) {
      debugLogger.warn(
        `loadSession: detected ${gaps.length} unrecoverable history gap(s) ` +
          `for session ${sessionId}: ` +
          gaps
            .map(
              (g) =>
                `child=${g.childUuid} missingParent=${g.missingParentUuid}`,
            )
            .join('; '),
      );
    }

    const lastMessage = messages[messages.length - 1];
    stats ??= fs.statSync(filePath);

    const conversation: ConversationRecord = {
      sessionId: firstRecord.sessionId,
      projectHash: this.projectHash,
      startTime: firstRecord.timestamp,
      lastUpdated: new Date(stats.mtimeMs).toISOString(),
      messages,
    };

    // Extract file history snapshots for /rewind across resume
    const fileHistorySnapshots: FileHistorySnapshot[] = [];
    const seenPromptIds = new Map<string, number>();
    for (const msg of messages) {
      if (
        msg.type === 'system' &&
        msg.subtype === 'file_history_snapshot' &&
        msg.systemPayload
      ) {
        const payload = msg.systemPayload as FileHistorySnapshotRecordPayload;
        if (!Array.isArray(payload?.snapshots)) continue;
        let deserialized: FileHistorySnapshot[];
        try {
          deserialized = deserializeSnapshots(payload.snapshots);
        } catch (e) {
          debugLogger.warn(
            `loadSession: skipping malformed file_history_snapshot: ${e}`,
          );
          continue;
        }
        for (const s of deserialized) {
          const existingIdx = seenPromptIds.get(s.promptId);
          if (existingIdx !== undefined) {
            fileHistorySnapshots[existingIdx] = s;
          } else {
            seenPromptIds.set(s.promptId, fileHistorySnapshots.length);
            fileHistorySnapshots.push(s);
          }
        }
      }
    }
    const cappedSnapshots =
      fileHistorySnapshots.length > MAX_SNAPSHOTS
        ? fileHistorySnapshots.slice(-MAX_SNAPSHOTS)
        : fileHistorySnapshots;
    const activeBranchRecords = includeActiveSideArtifactRecords(
      records,
      messages,
    );
    const artifactSnapshot = rebuildSessionArtifactSnapshot(
      activeBranchRecords,
      firstRecord.sessionId,
    );

    return {
      conversation,
      filePath,
      lastCompletedUuid: lastMessage.uuid,
      fileHistorySnapshots:
        cappedSnapshots.length > 0 ? cappedSnapshots : undefined,
      ...(artifactSnapshot ? { artifactSnapshot } : {}),
      historyGaps: gaps.length > 0 ? gaps : undefined,
    };
  }

  /**
   * Removes a session by its session ID.
   *
   * @param sessionId The session ID to remove
   * @returns true if removed, false if not found
   */
  async removeSession(sessionId: string): Promise<boolean> {
    const removed = await this.removeSessionFiles(sessionId);
    if (removed) {
      await this.removeSessionOrganization(sessionId);
    }
    return removed;
  }

  /**
   * Usage salvage wrapper enforcing the "never blocks deletion" contract at
   * the call site: persistUsageBeforeTranscriptDeletion catches its own
   * errors, but this second layer keeps the guarantee structural rather
   * than an implementation detail of another module.
   */
  private async salvageUsageBestEffort(transcriptPath: string): Promise<void> {
    try {
      await persistUsageBeforeTranscriptDeletion(transcriptPath);
    } catch (error) {
      this.warn(
        `usage salvage failed for ${transcriptPath}: ${error}; deleting anyway`,
      );
    }
  }

  private async removeSessionFiles(sessionId: string): Promise<boolean> {
    if (!isValidSessionFileName(`${sessionId}.jsonl`)) {
      return false;
    }

    try {
      const activePath = this.getSessionFilePath(sessionId, 'active');
      const active = await this.readProjectSessionHead(sessionId, activePath);
      if (active) {
        // #7384: the usage-history rebuild reads transcripts, so salvage
        // the session's usage summary before the file is gone. Never
        // blocks deletion (the salvage swallows its own errors).
        await this.salvageUsageBestEffort(activePath);
        this.removeFileIfExists(activePath);
        const archivedPath = this.getSessionFilePath(sessionId, 'archived');
        if (fs.existsSync(archivedPath)) {
          // When both copies co-exist (e.g. an interrupted archive), the
          // active transcript may hold no telemetry while the archived one
          // carries the session's history — salvage it too. The dedup
          // guard inside the salvage makes this a no-op whenever the
          // active copy already produced a record.
          await this.salvageUsageBestEffort(archivedPath);
          this.removeFileIfExists(archivedPath);
        }
        this.removeWorktreeSidecars(sessionId);
        this.removeFileHistoryBackups(sessionId);
        return true;
      }
      const archivedPath = this.getSessionFilePath(sessionId, 'archived');
      const archived = await this.readProjectSessionHead(
        sessionId,
        archivedPath,
      );
      if (!archived) {
        return false;
      }
      await this.salvageUsageBestEffort(archivedPath);
      this.removeFileIfExists(archivedPath);
      this.removeWorktreeSidecars(sessionId);
      this.removeFileHistoryBackups(sessionId);
      return true;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return false;
      }
      throw error;
    }
  }

  async archiveSessions(
    sessionIds: string[],
    options: ArchiveSessionsOptions = {},
  ): Promise<ArchiveSessionsResult> {
    const archived: string[] = [];
    const alreadyArchived: string[] = [];
    const notFound: string[] = [];
    const errors: Array<{ sessionId: string; error: Error }> = [];

    for (const sessionId of [...new Set(sessionIds)]) {
      try {
        if (!isValidSessionFileName(`${sessionId}.jsonl`)) {
          notFound.push(sessionId);
          continue;
        }
        if (options.knownLocation !== 'active') {
          const location = await this.getSessionLocation(sessionId);
          if (location === undefined) {
            notFound.push(sessionId);
            continue;
          }
          if (location === 'archived') {
            alreadyArchived.push(sessionId);
            continue;
          }
          if (location === 'conflict') {
            throw new Error(`Session archive conflict: ${sessionId}`);
          }
        }

        const sourcePath = this.getSessionFilePath(sessionId, 'active');
        const targetPath = this.getSessionFilePath(sessionId, 'archived');
        if (fs.existsSync(targetPath)) {
          throw new Error(`Session archive conflict: ${sessionId}`);
        }

        fs.mkdirSync(this.getArchiveChatsDir(), { recursive: true });
        const activeSidecar = this.getWorktreeSessionPathForState(
          sessionId,
          'active',
        );
        const archivedSidecar = this.getWorktreeSessionPathForState(
          sessionId,
          'archived',
        );
        try {
          fs.renameSync(sourcePath, targetPath);
        } catch (error) {
          throw this.sessionFileMoveError('archive', error);
        }
        try {
          this.moveOptionalFile(activeSidecar, archivedSidecar);
        } catch (sidecarError) {
          this.warn(
            `archiveSessions: failed to move worktree sidecar for ${sessionId} from ${activeSidecar} to ${archivedSidecar}: ${sidecarError}`,
          );
        }
        archived.push(sessionId);
      } catch (error) {
        errors.push({
          sessionId,
          error: error instanceof Error ? error : new Error(String(error)),
        });
      }
    }

    return { archived, alreadyArchived, notFound, errors };
  }

  async unarchiveSessions(
    sessionIds: string[],
    options: UnarchiveSessionsOptions = {},
  ): Promise<UnarchiveSessionsResult> {
    const unarchived: string[] = [];
    const alreadyActive: string[] = [];
    const notFound: string[] = [];
    const errors: Array<{ sessionId: string; error: Error }> = [];

    for (const sessionId of [...new Set(sessionIds)]) {
      try {
        if (options.knownLocation !== 'archived') {
          const location = await this.getSessionLocation(sessionId);
          if (location === undefined) {
            notFound.push(sessionId);
            continue;
          }
          if (location === 'active') {
            alreadyActive.push(sessionId);
            continue;
          }
          if (location === 'conflict') {
            throw new Error(`Session archive conflict: ${sessionId}`);
          }
        }

        const sourcePath = this.getSessionFilePath(sessionId, 'archived');
        const targetPath = this.getSessionFilePath(sessionId, 'active');
        if (fs.existsSync(targetPath)) {
          throw new Error(`Session archive conflict: ${sessionId}`);
        }

        const archivedSidecar = this.getWorktreeSessionPathForState(
          sessionId,
          'archived',
        );
        const activeSidecar = this.getWorktreeSessionPathForState(
          sessionId,
          'active',
        );
        fs.mkdirSync(path.dirname(targetPath), { recursive: true });
        try {
          fs.renameSync(sourcePath, targetPath);
        } catch (error) {
          throw this.sessionFileMoveError('unarchive', error);
        }
        try {
          this.moveOptionalFile(archivedSidecar, activeSidecar);
        } catch (sidecarError) {
          this.warn(
            `unarchiveSessions: failed to move worktree sidecar for ${sessionId} from ${archivedSidecar} to ${activeSidecar}: ${sidecarError}`,
          );
        }
        unarchived.push(sessionId);
      } catch (error) {
        errors.push({
          sessionId,
          error: error instanceof Error ? error : new Error(String(error)),
        });
      }
    }

    return { unarchived, alreadyActive, notFound, errors };
  }

  /**
   * Removes multiple sessions in one call.
   *
   * Each session is processed independently — a failure on one does not
   * abort the rest. Sessions that don't exist (or belong to a different
   * project) are reported in {@link notFound}; thrown filesystem
   * errors are surfaced per-id in {@link errors} so callers can decide
   * whether to retry.
   *
   * @param sessionIds IDs to remove. Duplicates are de-duplicated.
   * @returns Per-id outcomes: which were removed, which were not found,
   *   and which threw an error.
   */
  async removeSessions(sessionIds: string[]): Promise<RemoveSessionsResult> {
    const removed: string[] = [];
    const notFound: string[] = [];
    const errors: Array<{ sessionId: string; error: Error }> = [];

    const uniqueSessionIds = [...new Set(sessionIds)];
    const results = await Promise.allSettled(
      uniqueSessionIds.map((sessionId) => this.removeSessionFiles(sessionId)),
    );

    for (let i = 0; i < results.length; i++) {
      const sessionId = uniqueSessionIds[i];
      if (sessionId === undefined) continue;

      const result = results[i];
      if (result.status === 'fulfilled') {
        if (result.value) {
          removed.push(sessionId);
        } else {
          notFound.push(sessionId);
        }
      } else {
        errors.push({ sessionId, error: result.reason as Error });
      }
    }

    await this.removeSessionOrganizations(removed);

    return { removed, notFound, errors };
  }

  /**
   * Renames a session by appending a custom_title system record to its JSONL file.
   *
   * @param sessionId The session ID to rename
   * @param title The new custom title
   * @param titleSource Where the title came from. Defaults to `'manual'` so
   *   existing callers are unchanged — pass `'auto'` only for titles produced
   *   by the auto-title generator.
   * @returns true if renamed successfully, false if session not found
   * @remarks Only checks active sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  async renameSession(
    sessionId: string,
    title: string,
    titleSource: TitleSource = 'manual',
  ): Promise<boolean> {
    if (!isValidSessionFileName(`${sessionId}.jsonl`)) {
      return false;
    }
    const chatsDir = this.getChatsDir();
    const filePath = path.join(chatsDir, `${sessionId}.jsonl`);

    try {
      // Verify the file exists and belongs to this project
      const records = await jsonl.readLines<ChatRecord>(filePath, 1);
      if (records.length === 0) {
        return false;
      }

      if (
        !(await this.sessionBelongsToCurrentProject(sessionId, records[0].cwd))
      ) {
        return false;
      }

      // Read the last record's UUID so the custom_title record is properly
      // chained into the parent history.  reconstructHistory() walks from the
      // tail record upward via parentUuid; a null parentUuid would sever the
      // chain and cause the session to appear empty on next load.
      const lastUuid = this.readLastRecordUuid(filePath);

      // Append a custom_title system record. `renameSession` is the
      // fallback path when no live recording service is attached (e.g., from
      // the WebUI or VSCode extension). Callers pass `titleSource='auto'`
      // only when the title came from the auto-generator; defaults to
      // 'manual' for explicit user renames.
      const titleRecord: ChatRecord = {
        uuid: randomUUID(),
        parentUuid: lastUuid,
        sessionId,
        timestamp: new Date().toISOString(),
        type: 'system',
        subtype: 'custom_title',
        cwd: records[0].cwd,
        version: records[0].version,
        systemPayload: { customTitle: title, titleSource },
      };
      jsonl.writeLineSync(filePath, titleRecord);
      return true;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return false;
      }
      throw error;
    }
  }

  /**
   * Forks a session to a new sessionId.
   *
   * Reads the source JSONL into memory, reconstructs the active record chain,
   * rewrites every record's `sessionId` to `newSessionId`, stamps `cwd` to this
   * service's project root, rebuilds the `parentUuid` chain so the fork is a
   * linear continuation, stamps `forkedFrom: { sessionId, messageUuid }` on
   * every copied record for audit, and writes the result to `<newId>.jsonl`.
   *
   * Mirrors Claude Code's `/branch` storage model: full in-memory copy + per-
   * message forkedFrom (see claude-code/src/commands/branch/branch.ts).
   *
   * The source file is not modified.
   *
   * @throws If source does not exist, source is empty, source belongs to a
   *   different project, or the target file already exists.
   * @remarks Only checks active source sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  async forkSession(
    sourceSessionId: string,
    newSessionId: string,
  ): Promise<{ filePath: string; copiedCount: number }> {
    if (!isValidSessionFileName(`${sourceSessionId}.jsonl`)) {
      throw new Error(`Invalid source sessionId: ${sourceSessionId}`);
    }
    if (!isValidSessionFileName(`${newSessionId}.jsonl`)) {
      throw new Error(`Invalid new sessionId: ${newSessionId}`);
    }

    const chatsDir = this.getChatsDir();
    const sourcePath = path.join(chatsDir, `${sourceSessionId}.jsonl`);
    const targetPath = path.join(chatsDir, `${newSessionId}.jsonl`);

    // Read + parse the full source transcript.
    const records = await jsonl.read<ChatRecord>(sourcePath);
    if (records.length === 0) {
      throw new Error(`Source session not found or empty: ${sourceSessionId}`);
    }

    if (
      !(await this.sessionBelongsToCurrentProject(
        sourceSessionId,
        records[0].cwd,
      ))
    ) {
      throw new Error(
        `Source session does not belong to current project: ${sourceSessionId}`,
      );
    }

    // Copy only the active branch. Rewind leaves old records in the JSONL as
    // abandoned parentUuid branches; copying raw records would resurrect them.
    const { messages: activeMessages } = this.reconstructHistory(records);
    const sourceRecords = includeActiveSideArtifactRecords(
      records,
      activeMessages,
    ).filter(
      // A fork is a fresh top-level session with its own creation metadata.
      // Inheriting either record would falsely attribute the fork to the
      // source session's parent or creator.
      (record) =>
        !(
          record.type === 'system' &&
          (record.subtype === 'parent_session' ||
            record.subtype === 'session_source')
        ),
    );
    if (sourceRecords.length === 0) {
      throw new Error(`Source session not found or empty: ${sourceSessionId}`);
    }

    // Rebuild the parentUuid chain in active-history order so the fork is a
    // clean linear descendant. `forkedFrom` captures the origin of each
    // message.
    let prevUuid: string | null = null;
    const remappedArtifactIds = new Map<string, string>();
    const forked: ChatRecord[] = sourceRecords.map((record) => {
      const isArtifactRecord = isSessionArtifactRecord(record);
      const systemPayload = remapSystemPayloadForFork(
        record,
        sourceSessionId,
        newSessionId,
        remappedArtifactIds,
      );
      const next: ChatRecord = {
        ...record,
        sessionId: newSessionId,
        cwd: this.projectRoot,
        systemPayload,
        parentUuid: isArtifactRecord ? record.parentUuid : prevUuid,
        forkedFrom: {
          sessionId: sourceSessionId,
          messageUuid: record.uuid,
        },
      };
      if (!isArtifactRecord) {
        prevUuid = record.uuid;
      }
      return next;
    });

    // File-history snapshots are side-channel system records used by /rewind.
    // They may not sit on the active message leaf copied above, and copied
    // records may still point at the source session's prompt ids. Remap and
    // top up snapshots explicitly so /branch sessions expose /rewind/snapshots
    // immediately after they become live.
    const sourceSession = await this.loadSession(sourceSessionId);
    const existingSnapshotPromptIds =
      collectFileHistorySnapshotPromptIds(forked);
    const remappedSnapshots = sourceSession?.fileHistorySnapshots
      ?.map((snapshot) =>
        remapSnapshotPromptId(snapshot, sourceSessionId, newSessionId),
      )
      .filter((snapshot) => !existingSnapshotPromptIds.has(snapshot.promptId));
    if (remappedSnapshots?.length) {
      const snapshotRecord: ChatRecord = {
        uuid: randomUUID(),
        parentUuid: prevUuid,
        sessionId: newSessionId,
        type: 'system',
        subtype: 'file_history_snapshot',
        timestamp: new Date().toISOString(),
        cwd: this.projectRoot,
        version: records[0].version,
        systemPayload: {
          snapshots: remappedSnapshots.map(serializeSnapshot),
        },
      };
      forked.push(snapshotRecord);
    }

    fs.mkdirSync(chatsDir, { recursive: true });
    const body = forked.map((r) => JSON.stringify(r)).join('\n') + '\n';

    // Exclusive create: one syscall that both asserts "file doesn't exist"
    // and opens for writing, eliminating the TOCTOU window between a
    // separate existsSync check and writeFileSync. Also guarantees we
    // never silently overwrite an existing session file.
    let fd: number;
    try {
      fd = fs.openSync(targetPath, 'wx', 0o600);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'EEXIST') {
        throw new Error(`Target session file already exists: ${newSessionId}`);
      }
      throw err;
    }
    let targetComplete = false;
    try {
      try {
        fs.writeFileSync(fd, body, { encoding: 'utf8' });
      } finally {
        fs.closeSync(fd);
      }

      await copyFileHistoryBackups(sourceSessionId, newSessionId);
      targetComplete = true;
    } finally {
      if (!targetComplete) {
        try {
          this.removeFileIfExists(targetPath);
        } catch (cleanupError) {
          this.warn(
            `forkSession: failed to clean up incomplete target ${newSessionId}: ${cleanupError}`,
          );
        }
        try {
          this.removeFileHistoryBackups(newSessionId);
        } catch (cleanupError) {
          this.warn(
            `forkSession: failed to clean up file history for incomplete target ${newSessionId}: ${cleanupError}`,
          );
        }
      }
    }

    return { filePath: targetPath, copiedCount: forked.length };
  }

  /**
   * Gets the custom title for a session by reading from its JSONL file.
   *
   * @param sessionId The session ID to look up
   * @returns The custom title, or undefined if none set
   * @remarks Only checks active sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  getSessionTitle(sessionId: string): string | undefined {
    if (!isValidSessionFileName(`${sessionId}.jsonl`)) {
      return undefined;
    }
    const chatsDir = this.getChatsDir();
    const filePath = path.join(chatsDir, `${sessionId}.jsonl`);
    return this.readSessionTitleFromFile(filePath);
  }

  /**
   * Finds sessions by custom title.
   * Returns all matching sessions ordered by most recent first.
   *
   * @param title The custom title to search for (case-insensitive exact match)
   * @returns Array of matching session list items
   * @remarks Only searches active sessions. Archived title search is not
   * supported.
   */
  async findSessionsByTitle(title: string): Promise<SessionListItem[]> {
    const normalizedTitle = title.toLowerCase().trim();
    const matches: SessionListItem[] = [];
    const chatsDir = this.getChatsDir();

    // Scan all session files directly rather than paging through
    // listSessions(): the mtime-only cursor there uses a strict `<` boundary,
    // so sessions that share an mtime with the page's last entry are skipped,
    // which would silently drop valid title matches.
    let fileNames: string[];
    try {
      fileNames = fs.readdirSync(chatsDir);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return matches;
      }
      throw error;
    }

    const files: Array<{ name: string; mtime: number }> = [];
    for (const name of fileNames) {
      if (!isValidSessionFileName(name)) continue;
      const filePath = path.join(chatsDir, name);
      try {
        const stats = fs.statSync(filePath);
        files.push({ name, mtime: stats.mtimeMs });
      } catch {
        continue;
      }
    }

    // Sort most-recent first, with filename as a stable tie-breaker so runs
    // are deterministic even when multiple files share an mtime.
    files.sort((a, b) => b.mtime - a.mtime || a.name.localeCompare(b.name));

    // Pool the tail-read buffer across files; the title scan in the loop
    // body is otherwise the dominant alloc cost when many candidates exist.
    const tailBuffer = Buffer.alloc(LITE_READ_BUF_SIZE);

    let filesProcessed = 0;
    for (const file of files) {
      if (filesProcessed >= MAX_FILES_TO_PROCESS) break;
      filesProcessed++;

      const filePath = path.join(chatsDir, file.name);

      // Cheap check first: tail-read the title and skip non-matches before
      // doing the full hydration work (first-record read, project filter,
      // prompt extraction).
      const titleInfo = this.readSessionTitleInfoFromFile(filePath, tailBuffer);
      if (titleInfo.title?.toLowerCase().trim() !== normalizedTitle) continue;

      const records = await jsonl.readLines<ChatRecord>(
        filePath,
        MAX_PROMPT_SCAN_LINES,
      );
      if (records.length === 0) continue;
      const firstRecord = records[0];

      if (
        !(await this.sessionBelongsToCurrentProject(
          firstRecord.sessionId,
          firstRecord.cwd,
        ))
      ) {
        continue;
      }

      const prompt = this.extractFirstPromptFromRecords(records);

      matches.push({
        sessionId: firstRecord.sessionId,
        cwd: firstRecord.cwd,
        startTime: firstRecord.timestamp,
        mtime: file.mtime,
        prompt,
        gitBranch: firstRecord.gitBranch,
        filePath,
        // messageCount intentionally omitted; see SessionListItem for
        // the rationale and `countSessionMessages` for on-demand use.
        customTitle: titleInfo.title,
        titleSource: titleInfo.source,
      });
    }

    return matches;
  }

  /**
   * Returns the customTitles in this project that start with `prefix`
   * (case-insensitive). Single project-wide scan — meant to replace
   * repeated `findSessionsByTitle()` probes when the caller needs to
   * pick the first free `(Branch N)` slot in memory.
   *
   * Skips the heavy hydration steps (message count, prompt extraction)
   * that `findSessionsByTitle` does — collision lookup only needs the
   * title and a project filter, so we read the first record only when
   * the title actually matches the prefix.
   *
   * @param prefix Case-insensitive title prefix to match.
   */
  async findSessionTitlesByPrefix(prefix: string): Promise<string[]> {
    const normalizedPrefix = prefix.toLowerCase().trim();
    const titles: string[] = [];
    const chatsDir = this.getChatsDir();

    let fileNames: string[];
    try {
      fileNames = fs.readdirSync(chatsDir);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return titles;
      }
      throw error;
    }

    let filesProcessed = 0;
    for (const name of fileNames) {
      if (!isValidSessionFileName(name)) continue;
      if (filesProcessed >= MAX_FILES_TO_PROCESS) break;
      filesProcessed++;

      const filePath = path.join(chatsDir, name);

      // Cheap tail-read to extract the title before doing any project-
      // filter work. Saves a per-file jsonl.readLines on the common
      // case where most sessions don't share this prefix.
      const titleInfo = this.readSessionTitleInfoFromFile(filePath);
      if (!titleInfo.title) continue;
      const normalizedTitle = titleInfo.title.toLowerCase().trim();
      if (!normalizedTitle.startsWith(normalizedPrefix)) continue;

      // Project filter — same semantics as findSessionsByTitle: scope
      // collisions to the current project so a fork in another project
      // can't make this one bump unnecessarily.
      try {
        const records = await jsonl.readLines<ChatRecord>(filePath, 1);
        if (records.length === 0) continue;
        if (
          !(await this.sessionBelongsToCurrentProject(
            records[0].sessionId,
            records[0].cwd,
          ))
        ) {
          continue;
        }
      } catch {
        continue;
      }

      titles.push(titleInfo.title);
    }

    return titles;
  }

  /**
   * Loads the most recent session for the current project.
   * Combines listSessions and loadSession for convenience.
   *
   * @returns Session data for resumption, or undefined if no sessions exist
   */
  async loadLastSession(): Promise<ResumedSessionData | undefined> {
    const result = await this.listSessions({ size: 1 });
    if (result.items.length === 0) {
      return;
    }
    return this.loadSession(result.items[0].sessionId);
  }

  /**
   * Checks if a session exists by its session ID.
   *
   * @param sessionId The session ID to check
   * @returns true if session exists and belongs to current project
   * @remarks Only checks active sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  async sessionExists(sessionId: string): Promise<boolean> {
    if (!isValidSessionFileName(`${sessionId}.jsonl`)) {
      return false;
    }
    const chatsDir = this.getChatsDir();
    const filePath = path.join(chatsDir, `${sessionId}.jsonl`);

    try {
      const records = await jsonl.readLines<ChatRecord>(filePath, 1);
      if (records.length === 0) {
        return false;
      }
      return this.sessionBelongsToCurrentProject(sessionId, records[0].cwd);
    } catch {
      return false;
    }
  }

  async sessionExistsInAnyState(sessionId: string): Promise<boolean> {
    try {
      const location = await this.getSessionLocation(sessionId);
      return location !== undefined;
    } catch {
      return true;
    }
  }
}

/**
 * Options for building API history from conversation.
 */
export interface BuildApiHistoryOptions {
  /**
   * Whether to strip thought parts from the history.
   * Thought parts are content parts that have `thought: true`.
   * Keeping thoughts ensures `reasoning_content` from reasoning models
   * (e.g. DeepSeek) is properly passed back in subsequent API calls.
   * @default false
   */
  stripThoughtsFromHistory?: boolean;
}

/**
 * Strips thought parts from a Content object.
 * Thought parts are identified by having `thought: true`.
 * Returns null if the content only contained thought parts.
 */
function stripThoughtsFromContent(content: Content): Content | null {
  if (!content.parts) return content;

  const filteredParts = content.parts.filter((part) => !(part as Part).thought);

  // If all parts were thoughts, remove the entire content
  if (filteredParts.length === 0) {
    return null;
  }

  return {
    ...content,
    parts: filteredParts,
  };
}

function copyContentForApiHistory(content: Content): Content {
  return {
    ...content,
    parts: content.parts?.map((part) => {
      if ('functionCall' in part && part.functionCall) {
        return {
          ...part,
          functionCall: {
            ...part.functionCall,
            args: part.functionCall.args
              ? { ...part.functionCall.args }
              : part.functionCall.args,
          },
        };
      }
      if ('functionResponse' in part && part.functionResponse) {
        return {
          ...part,
          functionResponse: {
            ...part.functionResponse,
          },
        };
      }
      return { ...part };
    }),
  };
}

function appendApiHistoryRecord(history: Content[], record: ChatRecord): void {
  if (!record.message) return;

  const message = copyContentForApiHistory(record.message as Content);
  if (record.subtype === 'mid_turn_user_message') {
    const previous = history.at(-1);
    if (previous?.role === 'user') {
      previous.parts = [...(previous.parts ?? []), ...(message.parts ?? [])];
      return;
    }
  }

  history.push(message);
}

/**
 * Builds the model-facing chat history (Content[]) from a reconstructed
 * conversation. This keeps UI history intact while applying chat compression
 * checkpoints for the API history used on resume.
 *
 * Strategy:
 * - Find the latest system/chat_compression record (if any).
 * - Use its compressedHistory snapshot as the base history.
 * - Append all messages after that checkpoint (skipping system records).
 * - If no checkpoint exists, return the linear message list (message field only).
 */
export function buildApiHistoryFromConversation(
  conversation: ConversationRecord,
  options: BuildApiHistoryOptions = {},
): Content[] {
  const { stripThoughtsFromHistory = false } = options;
  const { messages } = conversation;

  let lastCompressionIndex = -1;
  let compressedHistory: Content[] | undefined;

  messages.forEach((record, index) => {
    if (record.type === 'system' && record.subtype === 'chat_compression') {
      const payload = record.systemPayload as
        | ChatCompressionRecordPayload
        | undefined;
      if (payload?.compressedHistory) {
        lastCompressionIndex = index;
        compressedHistory = payload.compressedHistory;
      }
    }
  });

  if (compressedHistory && lastCompressionIndex >= 0) {
    const baseHistory: Content[] = compressedHistory.map(
      copyContentForApiHistory,
    );

    // Append everything after the compression record (newer turns)
    for (let i = lastCompressionIndex + 1; i < messages.length; i++) {
      const record = messages[i];
      if (record.type === 'system') continue;
      appendApiHistoryRecord(baseHistory, record);
    }

    if (stripThoughtsFromHistory) {
      return baseHistory
        .map(stripThoughtsFromContent)
        .filter((content): content is Content => content !== null);
    }
    return baseHistory;
  }

  // Fallback: return linear messages as Content[]
  const result: Content[] = [];
  for (const record of messages) {
    appendApiHistoryRecord(result, record);
  }

  if (stripThoughtsFromHistory) {
    return result
      .map(stripThoughtsFromContent)
      .filter((content): content is Content => content !== null);
  }
  return result;
}

function remapSnapshotPromptId(
  snapshot: FileHistorySnapshot,
  sourceSessionId: string,
  newSessionId: string,
): FileHistorySnapshot {
  const sourcePrefix = `${sourceSessionId}########`;
  if (!snapshot.promptId.startsWith(sourcePrefix)) {
    return snapshot;
  }
  return {
    ...snapshot,
    promptId: `${newSessionId}########${snapshot.promptId.slice(sourcePrefix.length)}`,
  };
}

function remapFileHistorySnapshotPayload(
  payload: ChatRecord['systemPayload'],
  sourceSessionId: string,
  newSessionId: string,
): ChatRecord['systemPayload'] {
  const filePayload = payload as FileHistorySnapshotRecordPayload | undefined;
  if (!Array.isArray(filePayload?.snapshots)) return payload;

  try {
    const snapshots = deserializeSnapshots(filePayload.snapshots).map(
      (snapshot) =>
        serializeSnapshot(
          remapSnapshotPromptId(snapshot, sourceSessionId, newSessionId),
        ),
    );
    return { snapshots };
  } catch {
    return payload;
  }
}

function remapSystemPayloadForFork(
  record: ChatRecord,
  sourceSessionId: string,
  newSessionId: string,
  remappedArtifactIds: Map<string, string>,
): ChatRecord['systemPayload'] {
  if (record.type !== 'system') return record.systemPayload;
  if (record.subtype === 'file_history_snapshot') {
    return remapFileHistorySnapshotPayload(
      record.systemPayload,
      sourceSessionId,
      newSessionId,
    );
  }
  if (
    record.subtype === 'session_artifact_event' ||
    record.subtype === 'session_artifact_snapshot'
  ) {
    return remapSessionArtifactPayloadForFork(
      record.systemPayload,
      sourceSessionId,
      newSessionId,
      remappedArtifactIds,
    ) as ChatRecord['systemPayload'];
  }
  return record.systemPayload;
}

function includeActiveSideArtifactRecords(
  records: ChatRecord[],
  activeRecords: ChatRecord[],
): ChatRecord[] {
  const activeByUuid = new Map(
    activeRecords.map((record) => [record.uuid, record]),
  );
  const activeUuids = new Set(activeByUuid.keys());
  const firstActiveUuid = activeRecords[0]?.uuid;
  const firstActiveIndex =
    firstActiveUuid === undefined
      ? -1
      : records.findIndex((record) => record.uuid === firstActiveUuid);
  const nextActiveUuidByIndex = new Map<number, string>();
  const nextBlockingUuidByIndex = new Map<number, string>();
  let nextActiveUuid: string | undefined;
  let nextBlockingUuid: string | undefined;
  for (let index = records.length - 1; index >= 0; index--) {
    if (nextActiveUuid !== undefined) {
      nextActiveUuidByIndex.set(index, nextActiveUuid);
    }
    if (nextBlockingUuid !== undefined) {
      nextBlockingUuidByIndex.set(index, nextBlockingUuid);
    }
    if (activeUuids.has(records[index]!.uuid)) {
      nextActiveUuid = records[index]!.uuid;
      nextBlockingUuid = undefined;
    } else if (
      !isSessionArtifactRecord(records[index]!) &&
      !isTailNeutralSideRecord(records[index]!)
    ) {
      nextBlockingUuid = records[index]!.uuid;
    }
  }
  const selected: ChatRecord[] = [];
  const includedSideArtifactUuids = new Set<string>();
  let previousActiveUuid: string | undefined;
  for (let index = 0; index < records.length; index++) {
    const record = records[index]!;
    const activeRecord = activeByUuid.get(record.uuid);
    if (activeRecord) {
      selected.push(activeRecord);
      activeByUuid.delete(record.uuid);
      previousActiveUuid = record.uuid;
      continue;
    }
    if (!isSessionArtifactRecord(record)) {
      continue;
    }
    const nextUuid = nextActiveUuidByIndex.get(index);
    const hasBlockingRecordBeforeNextActive =
      nextBlockingUuidByIndex.has(index);
    const isInActiveSegment =
      !hasBlockingRecordBeforeNextActive &&
      (nextUuid !== undefined
        ? activeUuids.has(nextUuid)
        : previousActiveUuid !== undefined &&
          activeUuids.has(previousActiveUuid));
    if (
      record.parentUuid !== null &&
      (activeUuids.has(record.parentUuid) ||
        includedSideArtifactUuids.has(record.parentUuid)) &&
      isInActiveSegment &&
      (record.parentUuid === previousActiveUuid ||
        includedSideArtifactUuids.has(record.parentUuid))
    ) {
      selected.push(record);
      includedSideArtifactUuids.add(record.uuid);
    } else if (
      record.parentUuid === null &&
      index < firstActiveIndex &&
      isInActiveSegment
    ) {
      selected.push(record);
      includedSideArtifactUuids.add(record.uuid);
    }
  }
  return selected;
}

function isTailNeutralSideRecord(record: ChatRecord): boolean {
  return record.type === 'system' && record.subtype === 'custom_title';
}

function collectFileHistorySnapshotPromptIds(
  records: ChatRecord[],
): Set<string> {
  const ids = new Set<string>();
  for (const record of records) {
    if (
      record.type !== 'system' ||
      record.subtype !== 'file_history_snapshot' ||
      !record.systemPayload
    ) {
      continue;
    }
    const payload = record.systemPayload as FileHistorySnapshotRecordPayload;
    if (!Array.isArray(payload.snapshots)) continue;
    try {
      for (const snapshot of deserializeSnapshots(payload.snapshots)) {
        ids.add(snapshot.promptId);
      }
    } catch {
      // Malformed snapshot records are ignored the same way loadSession does.
    }
  }
  return ids;
}

/**
 * Replays stored UI telemetry events to rebuild metrics when resuming a session.
 * Also restores the last prompt token count from the best available source.
 */
export function replayUiTelemetryFromConversation(
  conversation: ConversationRecord,
  sessionId?: string,
): ResumeTokenCounts | undefined {
  if (sessionId) {
    uiTelemetryService.resetSession(sessionId);
  } else {
    uiTelemetryService.reset();
  }

  for (const record of conversation.messages) {
    if (record.type !== 'system' || record.subtype !== 'ui_telemetry') {
      continue;
    }
    const payload = record.systemPayload as
      | UiTelemetryRecordPayload
      | undefined;
    const uiEvent = payload?.uiEvent;
    if (uiEvent) {
      uiTelemetryService.addEvent(uiEvent, sessionId);
    }
  }

  const resumeTokenCounts = getResumeTokenCounts(conversation);
  if (resumeTokenCounts !== undefined) {
    uiTelemetryService.setLastPromptTokenCount(
      resumeTokenCounts.promptTokenCount,
    );
  }
  return resumeTokenCounts;
}

export interface ResumeTokenCounts {
  promptTokenCount: number;
  outputTokenCount: number;
}

/**
 * Returns the best available prompt token count for resuming telemetry.
 * Walks backward through messages and returns the first valid value:
 * - The latest assistant's non-zero usage (promptTokenCount ?? totalTokenCount).
 * - The most recent chat compression checkpoint's newTokenCount.
 */
export function getResumePromptTokenCount(
  conversation: ConversationRecord,
): number | undefined {
  return getResumeTokenCounts(conversation)?.promptTokenCount;
}

/**
 * Returns the prompt and previous-response output token counts used to seed a
 * resumed chat. The prompt count restores the context anchor; the output
 * count preserves the output tokens appended after that prompt count was
 * reported, matching steady-state prompt estimation on the next send.
 */
export function getResumeTokenCounts(
  conversation: ConversationRecord,
): ResumeTokenCounts | undefined {
  for (let i = conversation.messages.length - 1; i >= 0; i--) {
    const record = conversation.messages[i];

    if (record.type === 'assistant') {
      const usage = record.usageMetadata;
      const candidate = usage?.promptTokenCount ?? usage?.totalTokenCount;
      if (candidate) {
        return {
          promptTokenCount: candidate,
          outputTokenCount: getUsageOutputTokenCountForPromptEstimate(usage),
        };
      }
    }

    if (record.type === 'system' && record.subtype === 'chat_compression') {
      const payload = record.systemPayload as
        | ChatCompressionRecordPayload
        | undefined;
      if (payload?.info) {
        return {
          promptTokenCount: payload.info.newTokenCount,
          outputTokenCount: 0,
        };
      }
    }
  }

  return undefined;
}

const MAX_BRANCH_COLLISION_SCAN = 99;

export async function computeUniqueBranchTitle(
  baseName: string,
  sessionService: SessionService,
): Promise<string> {
  const maxSuffixLen = ' (Branch 1234567890123)'.length;
  const trimmed = baseName
    .trim()
    .slice(0, SESSION_TITLE_MAX_LENGTH - maxSuffixLen);
  const taken = new Set(
    (await sessionService.findSessionTitlesByPrefix(`${trimmed} (Branch`)).map(
      (t) => t.toLowerCase().trim(),
    ),
  );
  const first = `${trimmed} (Branch)`;
  if (!taken.has(first.toLowerCase())) return first;
  for (let n = 2; n <= MAX_BRANCH_COLLISION_SCAN; n++) {
    const candidate = `${trimmed} (Branch ${n})`;
    if (!taken.has(candidate.toLowerCase())) return candidate;
  }
  return `${trimmed} (Branch ${Date.now()})`;
}
